on:
  push:
    branches:
      - main

jobs:
  deploy:
    - name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Build
        run: chmod +x ./scripts/buildprod.sh && ./scripts/buildprod.sh
